language: node_js

node_js:
  - "6"

env:
  - TAF_CONFIG=true

install:
  - npm install

before_script:
  - npm run release

script:
  - 'cd release/express-webpack-starter && nohup node dist/server.js & && curl localhost:3000'
